stages: [setup-ci, bdt-train]

#Variables to link
variables:
  EOS_SAMPLES: "/eos/project-a/atlas-ngt-wp21/samples/GlobalSamples"
  FILE: "/workspace/samples"
  WORK_DIR: "/workspace/workDir"
  PROJECT: "$CI_PROJECT_DIR" #Change to project folder (as sub-module)
  META_PATH: "/eos/project/a/atlas-ngt-wp21/meta-data/$GITLAB_USER_LOGIN/$CI_COMMIT_SHA/"
  GIT_SUBMODULE_STRATEGY: none

#Helper definition
default:
  before_script:
    - tf_v2() { conda activate tf_v2; }
    - tf_v3() { conda activate tf_v3; }
    - xgboost() { conda activate xgboost; }
    - pytorch() { conda activate pytorch; }
    - base() { conda activate base; }
    
#Stage file inclusion
include:
  - local: 'ci/_shared.yml'
  - local: 'ci/setup.yml'
  - local: 'ci/bdt.yml'
