stages: [hat-train, qat-train, hls-convert, fw-build]

#Variables to link
variables:
  EOS_SAMPLES: "/eos/project-a/atlas-ngt-wp21/samples/GlobalSamples/merged"
  FILE: "/workspace/samples"
  WORK_DIR: "/workspace/workDir"
  PROJECT: "$CI_PROJECT_DIR" #Change to project folder (as sub-module)

#Helper definition
default:
  before_script:
    - myenv() { conda activate myenv; }

#Stage where the model is optimised against hyper-parameters
hat-train:
  stage: hat-train
  tags: [cern-nextgen-h100]
  image: registry.cern.ch/atlas-ngt-wp21/train
  script:
    - echo "$EOS_PASSWORD" | kinit "$EOS_USERNAME@CERN.CH" > /dev/null
    - ln -s $EOS_SAMPLES/* $FILE
    - mkdir -p "$WORK_DIR"
    - ln -s $PROJECT/* $WORK_DIR
    - source ~/.bashrc
    - myenv
    - mkdir -p out/folder_0 out/folder_1 out/folder_2 out/folder_3 out/folder_4
  artifacts:
    paths: [out/]
    expire_in: 2 days

.qat-template:
  stage: qat-train
  tags: [cern-nextgen-h100]
  image: registry.cern.ch/atlas-ngt-wp21/train
  script:
    - echo "EOS_PASSWORD" | kinit "$EOS_USERNAME@CERN.CH" > /dev/null
    - ln -s $EOS_SAMPLES/* $FILE
    - mkdir -p "$WORK_DIR"
    - ln -s $PROJECT/* WORK_DIR
    - source ~/.bashrc
    - myenv
    - mkdir -p qat/$idx
  artifacts:
    paths: ["qat/"]
    expire_in: 2 days

qat-0:
  extends: .qat-template
  needs: [{job: hat-stage, artifacts: true}]
  dependencies: ["hat-stage"]
  variables: { IDX: "0" }
    
qat-1:
  extends: .qat-template
  needs: [{job: hat-stage, artifacts: true}]
  dependencies: ["hat-stage"]
  variables: { IDX: "1" }

qat-2:
  extends: .qat-template
  needs: [{job: hat-stage, artifacts: true}]
  dependencies: ["hat-stage"]
  variables: { IDX: "2" }

qat-3:
  extends: .qat-template
  needs: [{job: hat-stage, artifacts: true}]
  dependencies: ["hat-stage"]
  variables: { IDX: "3" }

qat-4:
  extends: .qat-template
  needs: [{job: hat-stage, artifacts: true}]
  dependencies: ["hat-stage"]
  variables: { IDX: "4" }
  
  
#Stage where quantisation aware training optimises for physics performances
# qat-train:
#   stage: qat-train
#   tags: [cern-nextgen-h100]
#   image: registry.cern.ch/atlas-ngt-wp21/train
#   parallel: 5
#   needs:
#     - job: hat-train
#       artifacts: true
#   variables:
#     QAT_IN_ROOT: "artifacts/hat"
#     QAT_OUT_ROOT: "artifacts/qat"
#   script: |
#     echo "[qat-train] shard ${CI_NODE_INDEX}/${CI_NODE_TOTAL}"
#     SHARD=$((CI_NODE_INDEX - 1))
#     IN_DIR="${QAT_IN_ROOT}/folder_${SHARD}"
#     OUT_DIR="${QAT_OUT_ROOT}/$dir_{SHARD}"
#     test -d "${IN_DIR}" || { echo "Missing ${IN_DIR}" >&2; exit 2; }
#     mkdir -p "${OUT_DIR}"
#     ls ${QAT_OUT_ROOT}/
#     source ~/.bashrc
#     conda init
#     conda activate myenv
#     python --version    
#   artifacts:
#     when: on_success
#     expire_in: 7 days
#     paths:
#       - artifacts/qat/

# #Conversion of model into HLS code for synthesis
# hls-convert:
#   stage: hls-convert
#   tags: [cern-nextgen-mi300x]
#   image: registry.cern.ch/atlas-ngt-wp21/hls4ml_only
#   parallel: 5
#   needs:
#     - job: qat-train
#       artifacts: true
#   variables:
#     HLT_OUT_ROOT: "artifacts/hls"
#   script: |
#     echo "[hls-convert] shard ${CI_NODE_INDEX}/${CI_NODE_TOTAL} using ${IN_DIR}"    
#     SHARD=$((CI_NODE_INDEX - 1))
#     IN_DIR="artifacts/qat/dir_${SHARD}"
#     OUT_DIR="${HLS_OUT_ROOT}/dir_${SHARD}"
#     test -d "${IN_DIR}" || { echo "Missing ${IN_DIR}" >&2; exit 2; }
#     mkdir -p "${OUT_DIR}"
#     source ~/.bashrc
#     conda init
#     conda activate myenv
#     python --version    
#   artifacts:
#     when: on_success
#     expire_in: 7 days
#     paths:
#       - artifacts/hls/

# #Firmware building (i.e. synthesis) - using CI4FPGA infrastructure
# fw-build:
#   stage: fw-build
#   tags: [fpga-large]
#   image: registry.cern.ch/ci4fpga/vivado:2024.1
#   parallel: 5
#   needs:
#     - job: hls-convert
#       artifacts: true
#   script: |
#     echo "[fw-build] collection all HLS shard outputs"
#   artifacts:
#     when: on_success
#     expire_in: 30 days
#     paths:
#       - artifacts/fw/
    

