# config.yml

exports:
  ENV_NAME: "jetSeeding" #Name of design
  CONT_NAME: "train_v2" #Name of the container
  CONT_LOC: "harbor" #Container location [harbor, cvmfs, custom]
  SAMPLE_PATH: "$HOME" #Path to samples
  SAMPLE_NAME: " " #Name of train sample
  SAMPLE_EOS: "no" #If sample is in eos
  PROJECT_FOLDER: "$HOME" #Folder to be copied/access in container
  PROJECT_NAME: " " #Name of specific project
  TEST_FOLDER: "$HOME" #[Optional] Path to test package folder
  TEST_PACKAGE: " " #[Optional] Testing software alogn (wp21_train)
  KRB_ACCOUNT: "ngtwp21" #Not in used currently
  KRB_PASSWORD: "" #Password for kerberos ticket
  KUBEFLOW_FILE: "no" #Generates or not a kubeflow file for running in NGT WP1.1 cluster
  JUPYTER_PORT: 8888 #Jupyter notebook port
  
metadata:
  DEV_USER: "ixiotidi" 
  DEV_EMAIL: "ioannis.xiotdis@cern.ch"
  CREATED: "2025-06-28"
  TIME_ZONE: "UTC+1"
  HOSTNAME: "atlas-ngt-wp21"
  SHELL: "bash"
